[project]
name = "smc_clustering"
version = "0.0.1"
description = "Research on entity clustering using SMC methods."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evaluate>=0.4.5",
    "flax",
    "jax",
    "jaxlib",
    "matplotlib",
    "nltk",
    "numpy",
    "optax",
    "pandas",
    "plotly",
    "pyarrow>=21.0.0",
    "pytorch-lightning",
    "scikit-learn",
    "scipy",
    "seaborn",
    "tokenizers",
    "torch",
    "torchaudio",
    "torchvision",
    "tqdm",
    "transformers",
    "unidecode",
    "wandb",
]

[build-system]
requires = ["uv_build>=0.7.19,<0.8.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["jupyter", "pyright", "pytest", "pytest-mock", "ruff"]

[project.optional-dependencies]
gpu = ["jax[cuda12]"]

[tool.pyright]
typeCheckingMode = "basic"
useLibraryCodeForTypes = false
pythonVersion = "3.12"
exclude = ["**/__pycache__", "**/.*"]
